// Components
import Head from 'next/head'
import Title from '@/components/common/Title/Title'
import SubTitle from '@/components/common/Subtitle/SubTitle'

// Styles
import styled from '@/styles/Home.module.scss'
import styledCardSorting from '@/styles/card-sorting.module.scss'

// Utilities
import Image from 'next/image'
import heroImage from '@/../public/estude/mulher-estudando.png'
import welcomeImage from '@/../public/miniCurso/mulher-acenando.png'
// Hooks
// Interfaces

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styled.containerHome}>
        <section className={`container ${styledCardSorting.hero}`}>
          <div className={styledCardSorting.texts}>
            <Title type="Default">Card Sorting</Title>
            <SubTitle type="Lg">
              Conheça mais sobre essa ferramenta bastante utilizada durante
              <br /> para trabalhar a arquitetura de informação de um site ou
              aplicativo!
            </SubTitle>
          </div>
          <Image src={heroImage} alt="mulher estudando" />
        </section>
        <section className={`${styledCardSorting.sectionWhite}`}>
          <div className={`container ${styledCardSorting.sectionWelcome}`}>
            <Image src={welcomeImage} alt="mulher acenando" />
            <div>
              <Title type="Sm">Seja bem-vindo(a)!</Title>
              <div className={styledCardSorting.containerSubtitle}>
                <SubTitle type="Lg">
                  Esse é um mini curso (mini mesmo) sobre Card Sorting
                </SubTitle>
                <SubTitle type="Lg">
                  Você vai entender o que ele é, o que faz e qual a sua
                  importância na hora de <br /> construir um projeto
                </SubTitle>
                <SubTitle type="Lg">
                  Pronto para comprar post-its? Vamos lá!
                </SubTitle>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
