type Filtro = {
  label: string
  key: string
}

const filtros: Filtro[] = [
  { label: 'Todos', key: 'todos' },
  { label: 'Back-End', key: 'backend' },
  { label: 'Front-End', key: 'frontend' },
  { label: 'Design', key: 'design' },
  { label: 'Cloud e Dados', key: 'cloud' },
  { label: 'Marketing e Bussiness', key: 'marketing' },
  { label: 'Idiomas', key: 'idiomas' },
  { label: 'Para mulheres', key: 'mulher' },
  { label: 'Para jovens', key: 'jovens' },
]

const bootcampObjetc = [
  {
    id: 1,
    image: 'https://meninadeux.com/assets/img/bootcamps/bootcampinhouiux.webp',
    title: 'Bootcampinho UI/UX',
    description: `O Bootcampinho Gratuito UI/UX Design tem como objetivo te ajudar nos primeiros 
            passos de sua jornada. Formulado com o objetivo de ser um ponto de partida o 
            curso é dividido entre etapas teóricas e práticas.
            Além disso, você será desafiado(a) durante todo o curso a criar um projeto de 
            UI/UX Design do início ao fim. Todas as aulas também contam com desafios e 
            materiais de aprofundamento para ajudar você a continuar seus estudos.
    `,
    link: 'https://sheisacreative.com.br/curso/bootcampinho-ui-ux-design',
    category: ['todos', 'design'],
  },

  {
    id: 2,
    image: 'https://meninadeux.com/assets/img/bootcamps/startbycapgemini.webp',
    title: 'Programa Start by Capgemini',
    description: `O Programa START da Capgemini foi criado para ajudar quem já é da área de TI ou  
            quem deseja mudar de carreira, a ingressar no mercado e conquistar independência 
            financeira para realizar seus sonhos, independentemente da sua idade.
            Você escolhe sua trilha nas principais plataformas e ainda tem a possibilidade 
            de contratação no final do treinamento! 
    `,
    link: 'https://startcapgemini.com.br/',
    category: ['todos', 'backend', 'cloud'],
  },
]

const cursoObjetc = [
  {
    id: 1,
    image: 'https://meninadeux.com/assets/img/cursos/1mio.webp',
    title: '1MiO',
    description: 'A iniciativa Um Milhão de Oportunidades (1MiO) é a maior articulação do Brasil pela inclusão produtiva de adolescentes e jovens no mundo do trabalho decente. No site tem diversos cursos, eventos e oportunidades de trabalho divulgadas!',
    link: 'https://1mio.com.br/feeds',
    category: ['todos'],
  },
  {
    id: 2,
    image: 'https://meninadeux.com/assets/img/cursos/adobeeduca.webp',
    title: 'Adobe Educa',
    description: 'A Adobe Educa é a plataforma de educação gratuita para todos os professores do Brasil! Aqui você encontra cursos com especialistas em todos os programas da Adobe Creative Cloud: design, ilustração, animação, produção de vídeo, editoração e muito mais.',
    link: 'https://por.adobe-educa.com',
    category: ['todos'],
  },
  {
    id: 3,
    image: 'https://meninadeux.com/assets/img/cursos/avamec.webp',
    title: 'AVAMEC',
    description: 'A AVAMEC é um ambiente virtual colaborativo de aprendizagem que permite a concepção, administração e desenvolvimento de diversos tipos de ações formativas, como cursos a distância, complemento a cursos presenciais, projetos de pesquisa, projetos colaborativos e diversas outras formas de apoio educacional à distância ao processo ensino-aprendizagem!',
    link: 'https://avamec.mec.gov.br/#/',
    category: ['todos'],
  },
  {
    id: 4,
    image: 'https://meninadeux.com/assets/img/cursos/amazonalexa.webp',
    title: 'Alexa Skills: Design de Voz',
    description: 'Aprenda as melhores práticas de design para skills da Alexa, você aprenderá a criar experiências de voz naturais e enriquecedoras.',
    link: 'https://build.amazonalexadev.com/cursoalexa-designdevoz.html',
    category: ['todos'],
  },
  {
    id: 5,
    image: 'https://meninadeux.com/assets/img/cursos/awari.webp',
    title: 'Cursos Introdutórios na Awari',
    description: 'A Awari oferece cursos gratuitos em Data Science, Programação, UX/UI design e outros. Para acessá-los, basta você clicar rolar até a seção de "Cursos em destaque"!',
    link: 'https://awari.com.br/#categorias',
    category: ['todos'],
  },
  {
    id: 6,
    image: 'https://meninadeux.com/assets/img/cursos/awsskillbuilder.webp',
    title: 'AWS Skill Builder',
    description: 'A Amazon criou o AWS Skill Builder, que é o seu centro de aprendizado para o desenvolvimento das habilidades de nuvem mais desejadas! A plataforma tem vários cursos sobre a cloud AWS',
    link: 'https://explore.skillbuilder.aws/learn',
    category: ['todos'],
  },
  {
    id: 7,
    image: 'https://meninadeux.com/assets/img/cursos/bancocentraldobrasil.webp',
    title: 'Branco Central do Brasil',
    description: 'O Banco Central do Brasil está oferecendo dois cursos online e gratuitos sobre finanças: Gestão de Finanças Pessoais e Formação de Multiplicadores da Série "Eu e Meu Dinheiro".',
    link: 'https://www.bcb.gov.br/cidadaniafinanceira/cursos',
    category: ['todos'],
  },
  {
    id: 8,
    image: 'https://meninadeux.com/assets/img/cursos/bolsagratis.webp',
    title: 'Bolsa Grátis',
    description: 'Aumente suas possibilidades profissionais com cursos exclusivos, de curta duração e totalmente gratuitos!',
    link: 'https://bolsagratis.com.br/busca-cursos/?f=&type=cursos_gratis&presencial=true&ead=true',
    category: ['todos'],
  },
  {
    id: 9,
    image: 'https://meninadeux.com/assets/img/cursos/cieesabervirtual.webp',
    title: 'CIEE - Saber Virtual',
    description: 'O CIEE Saber Virtual é uma plataforma de cursos que permite a realização totalmente a distância. Nesse portal, é possível realizar 5 trilhas de conhecimento, que foram feitas com a intenção de preparar estudantes para o mundo do trabalho, sendo que, aqueles que concluírem os cursos, terão direito a um certificado.',
    link: 'https://portal.ciee.org.br/para-voce/saber-virtual/',
    category: ['todos'],
  },
  {
    id: 10,
    image: 'https://meninadeux.com/assets/img/cursos/coliga.webp',
    title: 'co.liga',
    description: 'A co.liga aposta no potencial da economia criativa para a inclusão produtiva das juventudes que são públicos-alvo da escola. Os cursos são de temas que vão desde artes visuais até temas mais transversais.',
    link: 'https://coliga.digital/cursos',
    category: ['todos'],
  },
  {
    id: 11,
    image: 'https://meninadeux.com/assets/img/cursos/coursera.webp',
    title: 'Coursera (Inglês)',
    description: 'A Coursera é uma plataforma com cursos incríveis de empresas tops! Sério, lá tem muuuuitos cursos gratuitos e você ainda pode pedir financiamento em alguns deles, como o de UX Design do Google, viu?',
    link: 'https://www.coursera.org/search?query=user%20experience&index=prod_all_launched_products_term_optimization&skills=User%20Experience&skills=Design%20and%20Product&skills=User%20Research&skills=User%20Experience%20Design&skills=Writing&skills=User%20Interface&skills=Usability',
    category: ['todos'],
  },
  {
    id: 12,
    image: 'https://meninadeux.com/assets/img/cursos/crescacomogoogle.webp',
    title: 'Cresça com o Google',
    description: 'Aprenda habilidades digitais importantes para sua carreira ou negócio com as ferramentas e treinamentos gratuitos do Google',
    link: 'https://cresca.withgoogle.com/intl/pt-br/learn-skills/',
    category: ['todos'],
  },
  {
    id: 13,
    image: 'https://meninadeux.com/assets/img/cursos/cursae.webp',
    title: 'Cursae',
    description: 'Vários cursos online com certificado gratuitos: tem de Figma, programação com Minecraft, criação de jogos e muito mais!',
    link: 'https://www.cursae.com.br',
    category: ['todos'],
  },
  {
    id: 14,
    image: 'https://meninadeux.com/assets/img/cursos/cursoemvideo.webp',
    title: 'Curso em Vídeo',
    description: 'Turbine seu currículo com cursos gratuitos do Curso em Vídeo. Aprenda informática com cursos grátis feitos por especialistas.',
    link: 'https://www.cursoemvideo.com/cursos/',
    category: ['todos'],
  },
  {
    id: 15,
    image: 'https://meninadeux.com/assets/img/cursos/datascienceacademy.webp',
    title: 'Data Science Academy',
    description: 'A Data Science Academy é um portal de ensino a distância, focado em capacitação profissional em Data Science, Big Data, Inteligência Artificial, Internet das Coisas e muito mais!',
    link: 'https://www.datascienceacademy.com.br/cursosgratuitos',
    category: ['todos'],
  },
  {
    id: 16,
    image: 'https://meninadeux.com/assets/img/cursos/dio.webp',
    title: 'Digital Innovation One',
    description: 'A DIO é uma escola de programação que conecta seus alunos a empresas em busca de mão de obra tecnológica. Você encontra vários cursos, trilhas, bootcamps e ainda pode interagir com outros alunos!',
    link: 'https://dio.me/sign-up?ref=U5U6LS080B',
    category: ['todos'],
  },
  {
    id: 17,
    image: 'https://meninadeux.com/assets/img/cursos/digitalods.webp',
    title: 'Digital ODS',
    description: 'O 1MiO e a DIO se uniram para disponibilizar formação e capacitação em tecnologia com o objetivo de impactar e transformar a vida de jovens em situação de vulnerabilidade social nas periferias da região sudeste, tudo isso por meio de cursos na área tecnológica e do acesso à oportunidades no mercado de trabalho!',
    link: 'https://lp.digitalinnovation.one/digital-ods',
    category: ['todos'],
  },
  {
    id: 18,
    image: 'https://meninadeux.com/assets/img/cursos/educacaolivre.webp',
    title: 'Educação Livre',
    description: 'O Edu Livre oferece mais de 150 trilhas de conhecimento em diferentes áreas de forma totalmente online e gratuita para quem quer se capacitar e transformar sua realidade!',
    link: 'https://www.edulivre.org.br',
    category: ['todos'],
  },
  {
    id: 19,
    image: 'https://meninadeux.com/assets/img/cursos/edx.webp',
    title: 'EDX (inglês)',
    description: 'A EDX é um site fundado por pesquisadores de Harvard e do MIT com o objetivo de tornar mais acessíveis os cursos dessas instituições',
    link: 'https://www.edx.org',
    category: ['todos'],
  },
  {
    id: 20,
    image: 'https://meninadeux.com/assets/img/cursos/escoladanuvem.webp',
    title: 'Escola da Nuvem',
    description: 'Organização sem fins lucrativos que prepara estudantes para carreiras na nuvem por meio de cursos gratuitos, interações com profissionais experientes em cloud computing e a força de empresas de tecnologia dispostas a contratar os alunos.',
    link: 'https://www.escoladanuvem.org/cursoss/',
    category: ['todos'],
  },
  {
    id: 21,
    image: 'https://meninadeux.com/assets/img/cursos/escoladotrabalhador.webp',
    title: 'Escola do Trabalhador 4.0',
    description: 'A Escola do Trabalhador é um programa de qualificação profissional que oferece cursos gratuitos em temas de tecnologia e produtividade, desde letramento digital até testes de carreira!',
    link: 'https://ead.escoladotrabalhador40.com.br',
    category: ['todos'],
  },
  {
    id: 22,
    image: 'https://meninadeux.com/assets/img/cursos/escolavirtualgov.webp',
    title: 'Escola Virtual Gov',
    description: 'O Governo Federal oferece cursos on-line e gratuitos de várias áreas de conhecimento! Você encontra cursos desde as áreas de design até metodologias ágeis e sustentabilidade!',
    link: 'https://www.escolavirtual.gov.br',
    category: ['todos'],
  },
  {
    id: 23,
    image: 'https://meninadeux.com/assets/img/cursos/estacaohack.webp',
    title: 'Estação Hack',
    description: 'O Cel.Lep, parceiro da Estação Hack, oferece cursos gratuitos, como os de design de UX e ui, desenvolvimento front-end, back-end e mobile, e inglês instrumental para tecnologia.',
    link: 'https://br.cellep.com/estacao-hack-sp/',
    category: ['todos'],
  },
  {
    id: 24,
    image: 'https://meninadeux.com/assets/img/cursos/estudarfora.webp',
    title: 'Estudar Fora',
    description: 'Tire seus sonhos do papel com os cursos da fundação estudar! Os cursos vão apoiar você no seu desenvolvimento pessoal e profissional.',
    link: 'https://www.estudarfora.org.br/cursos/',
    category: ['todos'],
  },
  {
    id: 25,
    image: 'https://meninadeux.com/assets/img/cursos/eucapacito.webp',
    title: 'Eu Capacito',
    description: 'Projeto social que tem o objetivo de formar uma legião de profissionais para a economia digital, promovendo a capacitação profissional gratuita em quatro áreas principais: tech, empreendedorismo, soft skills e fluência digital.',
    link: 'https://eucapacito.com.br',
    category: ['todos'],
  },
  {
    id: 26,
    image: 'https://meninadeux.com/assets/img/cursos/fecap.webp',
    title: 'FECAP',
    description: 'A FECAP (Fundação Escola de Comércio Álvares Penteado) oferece vários cursos gratuitos em diversas áreas, focando em soft skills, principalmente em liderança e carreira.',
    link: 'https://www.FECAP.br/curta-duracao-gratuito/',
    category: ['todos'],
  },
  {
    id: 27,
    image: 'https://meninadeux.com/assets/img/cursos/bradesco.webp',
    title: 'Fundação Bradesco - Escola Virtual',
    description: 'Mais de 90 cursos gratuitos e totalmente online em diversas áreas, como administração, contabilidade e finanças, desenvolvimento pessoal e profissional, educação e tecnologia.',
    link: 'https://www.ev.org.br',
    category: ['todos'],
  },
  {
    id: 28,
    image: 'https://meninadeux.com/assets/img/cursos/fgv.webp',
    title: 'Fundação Getúlio Vargas',
    description: 'A FGV foi a primeira brasileira a integrar o consórcio de instituições de ensino que oferecem conteúdos e materiais didáticos gratuitos online e possui uma variedade de cursos gratuitos em diversas áreas.',
    link: 'https://educacao-executiva.fgv.br/cursos/gratuitos',
    category: ['todos'],
  },
  {
    id: 29,
    image: 'https://meninadeux.com/assets/img/cursos/fiap.webp',
    title: 'FIAP On',
    description: 'Em conjunto com o Eu Capacito, programa liderado pelo Instituto It Mídia, a FIAP oferece a você 20 Nano Courses gratuitos. São cursos de 40 a 160 horas nas áreas de tecnologia, inovação e negócios.',
    link: 'https://on.fiap.com.br/local/programaeucapacito/',
    category: ['todos'],
  },
  {
    id: 30,
    image: 'https://meninadeux.com/assets/img/cursos/ginead.webp',
    title: 'Ginead',
    description: 'No Ginead você encontra cursos gratuitos nas mais diversas áreas de conhecimento, além de poder estudar a distância em uma plataforma intuitiva, de qualquer lugar e quando quiser! Atenção: o certificado é pago.',
    link: 'https://www.Ginead.com.br',
    category: ['todos'],
  },
  {
    id: 31,
    image: 'https://meninadeux.com/assets/img/cursos/googleskillshop.webp',
    title: 'Google Skillshop',
    description: 'Acesse o treinamento on-line gratuito para desenvolver habilidades nas ferramentas do Google Workspace. Aprenda no seu próprio ritmo e obtenha a certificação de produtos do Google ao longo do caminho.',
    link: 'https://skillshop.exceedlms.com/student/catalog/browse',
    category: ['todos'],
  },
  {
    id: 32,
    image: 'https://meninadeux.com/assets/img/cursos/hiacademy.webp',
    title: 'Hi Academy',
    description: 'A Hi Academy leva até a sua cidade um curso essencial para quem deseja trabalhar ou se aperfeiçoar no área de atendimento ao cliente.',
    link: 'https://hiacademy.com.br',
    category: ['todos'],
  },
  {
    id: 33,
    image: 'https://meninadeux.com/assets/img/cursos/houseacademy.webp',
    title: 'House Academy',
    description: 'A House Academy vem com o propósito de expandir os conhecimentos das pessoas sobre as carreiras digitais! Os cursos sobre conceitos básicos são gratuitos e contam com conteúdos incríveis.',
    link: 'https://digital-house.mykajabi.com',
    category: ['todos'],
  },
  {
    id: 34,
    image: 'https://meninadeux.com/assets/img/cursos/ifrs.webp',
    title: 'IFRS',
    description: 'O Instituto Federal do Rio Grande do Sul abriu novas vagas para as turmas de 2022 dos seus cursos gratuitos e online em várias áreas, desde tecnologia até ambiente e saúde.',
    link: 'https://moodle.IFRS.edu.br/course/index.php?categoryid=38',
    category: ['todos'],
  },
  {
    id: 35,
    image: 'https://meninadeux.com/assets/img/cursos/timtec.webp',
    title: 'Instituto TIM - Tim Tec',
    description: 'Aqui você encontra todos os cursos já produzidos e publicados por tim tec ou seus parceiros. Eles podem ser acessados e cursados direto na plataforma, por qualquer pessoa, gratuitamente.',
    link: 'https://cursos.timtec.com.br/courses',
    category: ['todos'],
  },
  {
    id: 36,
    image: 'https://meninadeux.com/assets/img/cursos/institutotie.webp',
    title: 'Instituto Tiê',
    description: 'O Instituto Tiê está oferecendo minicursos sobre comunicação não violenta, onde você vai aprender sobre empatia, comunicação e receber dicas!',
    link: 'https://institutotie.com.br/minicurso-gratuito-sobre-comunicacao-nao-violenta/',
    category: ['todos'],
  },
  {
    id: 37,
    image: 'https://meninadeux.com/assets/img/cursos/inspiraja.webp',
    title: 'Inspira JA',
    description: 'Na plataforma Inspira JA, você vai aprender sobre empreendedorismo, tecnologia, educação financeira, habilidades para o mercado de trabalho e muito mais em diferentes formatos!',
    link: 'https://inspiraja.org.br',
    category: ['todos'],
  },
  {
    id: 38,
    image: 'https://meninadeux.com/assets/img/cursos/ituring.webp',
    title: 'Ituring',
    description: 'O Ituring é um instituto de educação em tecnologia e negócios da era digital. Eles oferecem cursos de tecnologia em dados, negócios e programação.',
    link: 'https://www.Ituring.com.br/cursos/',
    category: ['todos'],
  },
  {
    id: 39,
    image: 'https://meninadeux.com/assets/img/cursos/ivyleague.webp',
    title: 'Ivy League - Cursos gratuitos',
    description: 'A plataforma ClassCentral está disponibilizando quase 500 cursos online gratuitos de universidades da Ivy League (como Harvard, Princeton, Yale e Columbia) que podem ser realizados da sua casa.',
    link: 'https://www.classcentral.com/collection/ivy-league-moocs',
    category: ['todos'],
  },
  {
    id: 40,
    image: 'https://meninadeux.com/assets/img/cursos/kultivi.webp',
    title: 'Kultivi - Cursos gratuitos',
    description: 'Na Kultivi você aprende Idiomas, se prepara para Concursos, OAB, Enem e se desenvolve pessoal e profissionalmente. Cursos gratuitos e com certificado para você ir mais longe.',
    link: 'https://kultivi.com',
    category: ['todos'],
  },
  {
    id: 41,
    image: 'https://meninadeux.com/assets/img/cursos/linkedinpremium.webp',
    title: 'LinkedIn Premium para Estudantes',
    description: 'O Linkedin está disponibilizando acesso premium gratuito a estudantes. É necessário confirmar que você estuda em uma instituição que seja elegível e que conceda diploma. Vantagens: Saber quem visualizou o seu perfil e verificar se aquela empresa está contratando, além de acesso aos cursos gratuitos com certificado do Linkedin Learning!',
    link: 'https://members.linkedin.com/pt-br/estudante/linkedin-premium',
    category: ['todos'],
  },
  {
    id: 42,
    image: 'https://meninadeux.com/assets/img/cursos/lumina.webp',
    title: 'Lumina - UFRGS',
    description: 'A Lumina é uma iniciativa da Universidade Federal do Rio Grande do Sul que disponibiliza 80 cursos online, gratuitos e com certificados.',
    link: 'https://lumina.UFRGS.br',
    category: ['todos'],
  },
  {
    id: 43,
    image: 'https://meninadeux.com/assets/img/cursos/metablueprint.webp',
    title: 'Meta Blueprint',
    description: 'Explore no seu próprio ritmo tutoriais detalhados que podem ajudar você a adquirir conhecimento sobre marketing digital!',
    link: 'https://www.facebookblueprint.com/student/catalog',
    category: ['todos'],
  },
  {
    id: 44,
    image: 'https://meninadeux.com/assets/img/cursos/microlins.webp',
    title: 'Microlins',
    description: 'A Microlins, empresa de cursos profissionalizantes, está oferecendo 4 cursos gratuitos, que variam desde libras até marketing pessoal!',
    link: 'https://www.Microlins.com.br/curso-gratis',
    category: ['todos'],
  },
  {
    id: 45,
    image: 'https://meninadeux.com/assets/img/cursos/microsoftlearn.webp',
    title: 'Microsoft Learn',
    description: 'O Microsoft Learn é a maneira mais fácil de aprender sobre produtos e serviços por meio de aprendizagem interativa baseada em tarefas com mais de 80 horas de conteúdo gratuito, localizado em 23 idiomas e abrangendo as plataformas Azure, Dynamics, Power Apps e Flow.',
    link: 'https://docs.microsoft.com/pt-br/learn/browse/',
    category: ['todos'],
  },
  {
    id: 46,
    image: 'https://meninadeux.com/assets/img/cursos/mundosenai.webp',
    title: 'Mundo SENAI',
    description: 'O Mundo SENAI é a plataforma perfeita onde você encontra cursos, vagas de emprego, orientação para sua carreira e muito mais!',
    link: 'https://loja.mundosenai.com.br',
    category: ['todos'],
  },
  {
    id: 47,
    image: 'https://meninadeux.com/assets/img/cursos/navedoconhecimento.webp',
    title: 'Nave do Conhecimento',
    description: 'A Nave do Conhecimento está com inscrições abertas para mais 13 mil vagas em diversos cursos gratuitos nas áreas de tecnologia, informática e empreendedorismo.',
    link: 'https://capacitacao.navedoconhecimento.rio',
    category: ['todos'],
  },
  {
    id: 48,
    image: 'https://meninadeux.com/assets/img/cursos/nicbr.webp',
    title: 'NIC.br',
    description: 'O NIC.br oferece vários cursos em diferentes áreas de forma online e totalmente gratuita! Têm cursos de IPv6, Intensivo da Escola de Governança da Internet no Brasil, Boas Práticas Operacionais para Sistemas Autônomos e muitos outros.',
    link: 'https://cursoseventos.nic.br/cursos/',
    category: ['todos'],
  },
  {
    id: 49,
    image: 'https://meninadeux.com/assets/img/cursos/poca.webp',
    title: 'POCA (UFSCAR)',
    description: 'A UFSCAR criou a POCA (Portal de Cursos Abertos) para oferecer ensino online e gratuito para o público. Tem muitos cursos de várias áreas que são muito bons!',
    link: 'https://cursos.poca.ufscar.br',
    category: ['todos'],
  },
  {
    id: 50,
    image: 'https://meninadeux.com/assets/img/cursos/portaltech.webp',
    title: 'Portal Tech',
    description: 'A Proz é referência em qualidade na Educação Profissional, com mais de 25 escolas no Brasil, e desenharam um programa para você, que quer começar uma carreira no mundo da tecnologia: um curso EAD, com atividades síncronas, em uma plataforma super engajadora e gameficada.',
    link: 'https://www.portaltechs.com',
    category: ['todos'],
  },
  {
    id: 51,
    image: 'https://meninadeux.com/assets/img/cursos/potenciatech.webp',
    title: 'Potência Tech',
    description: 'Mais do que uma plataforma, é um projeto que apoia a formação de profissionais de tecnologia por meio de cursos gratuitos, programas de bolsas de estudos, apoio à carreira e à entrada no mercado de trabalho!',
    link: 'https://potenciatech.com.br',
    category: ['todos'],
  },
  {
    id: 52,
    image: 'https://meninadeux.com/assets/img/cursos/prageralver.webp',
    title: '#PraGeralVer',
    description: 'O Grupo Boticário, em parceria com especialistas em audiodescrição, está oferecendo uma aula gratuita para sensibilizar e ensinar os requisitos mínimos para que as suas publicações e comunicação sejam acessíveis a todas as pessoas. E o melhor, você poderá acessar quando e de onde puder!',
    link: 'https://www.grupoboticario.com.br/inscricao/',
    category: ['todos'],
  },
  {
    id: 53,
    image: 'https://meninadeux.com/assets/img/cursos/maisprati.webp',
    title: '+PraTi',
    description: 'O +PraTi é uma iniciativa da sociedade sem fins lucrativos que busca encontrar e capacitar novos talentos da área de TI. Eles oferecem trilhas de conhecimento de maneira gratuita para quem quer dar os seus primeiros passos em sua jornada agora mesmo!',
    link: 'https://www.maisprati.com.br/trilhas/',
    category: ['todos'],
  },
  {
    id: 54,
    image: 'https://meninadeux.com/assets/img/cursos/prepposgraduacao.webp',
    title: 'Prep Pós-Graduação',
    description: 'O Prep Pós-Graduação é um curso completo e gratuito que te prepara para cursar uma pós-graduação fora do país!',
    link: 'https://materiais.estudarfora.org.br/curso-prep-pos-graduacao/',
    category: ['todos'],
  },
  {
    id: 55,
    image: 'https://meninadeux.com/assets/img/cursos/pucrs.webp',
    title: 'PUCRS',
    description: 'A PUCRS oferece os cursos "Produtividade, Gestão do Tempo e Propósito" e "Como Alcançar seus Objetivos Profissionais e Metas Financeiras" de forma gratuita em seu site para os interessados em alcançar novos patamares!',
    link: 'https://mkt.PUCRS.br/cursosgratuitos',
    category: ['todos'],
  },
  {
    id: 56,
    image: 'https://meninadeux.com/assets/img/cursos/punkmetrics.webp',
    title: 'Punk Metrics',
    description: 'A Punk Metrics oferece um curso de UX Metrics Básico de forma gratuita, que aborda conceitos sobre métricas de experiência e a importância do uso desses dados no processo de design.',
    link: 'https://punkmetrics.com/courses/UX-metrics-basico/',
    category: ['todos'],
  },
  {
    id: 57,
    image: 'https://meninadeux.com/assets/img/cursos/recode.webp',
    title: 'Recode',
    description: 'Por meio de formações virtuais e projetos que unem tecnologia e educação, a Recode qualifica jovens e adultos no uso de ferramentas digitais fundamentais para o período em que vivemos.',
    link: 'https://Recode.org.br',
    category: ['todos'],
  },
  {
    id: 58,
    image: 'https://meninadeux.com/assets/img/cursos/rockuniversity.webp',
    title: 'Rock University',
    description: 'O objetivo é unir todas as plataformas educacionais da Rock Content, e você terá acesso a todo conteúdo em um só lugar, o que te oferece a melhor experiência para continuar aprendendo Marketing Digital com a Rock University!',
    link: 'https://university.br.rockcontent.com',
    category: ['todos'],
  },
  {
    id: 59,
    image: 'https://meninadeux.com/assets/img/cursos/samsungocean.webp',
    title: 'Samsung Ocean',
    description: 'O Samsung Ocean é uma iniciativa da Samsung no Brasil que oferece capacitação tecnológica à comunidade e fomenta a criação de empresas de base tecnológica (startups).',
    link: 'https://www.oceanbrasil.com',
    category: ['todos'],
  },
  {
    id: 60,
    image: 'https://meninadeux.com/assets/img/cursos/sebrae.webp',
    title: 'SEBRAE',
    description: 'Centenas de cursos, trilhas, jogos e ebooks para você aprender quando e onde quiser.',
    link: 'https://www.SEBRAE.com.br/sites/PortalSEBRAE/cursosonline#',
    category: ['todos'],
  },
  {
    id: 61,
    image: 'https://meninadeux.com/assets/img/cursos/senai.webp',
    title: 'Senai',
    description: 'O SENAI está disponibilizando vários cursos gratuitos em diferentes áreas, desde tecnologia até manutenção de carros!',
    link: 'https://portalead.sp.senai.br/institucional/3722/3840/cursos-gratuitos',
    category: ['todos'],
  },
  {
    id: 62,
    image: 'https://meninadeux.com/assets/img/cursos/senaiplay.webp',
    title: 'Senai Play',
    description: 'Já pensou algum dia ser possível se qualificar por meio de vídeos ou podcasts no YouTube? Essa é a proposta do Senai Play! Unindo inovação e tecnologia, a plataforma tem como principal proposta disseminar conhecimentos e soluções sobre os mais variados segmentos de aprendizado industrial para todos.',
    link: 'https://senaiplay.senai.br',
    category: ['todos'],
  },
  {
    id: 63,
    image: 'https://meninadeux.com/assets/img/cursos/tramplay.webp',
    title: 'Tramplay - Introdução ao Design Thinking',
    description: 'Curso 100% gratuito que fala sobre o conceito, processo e etapas do Design Thinking.',
    link: 'https://Tramplay.com.br/p/curso-introducao-ao-design-thinking',
    category: ['todos'],
  },
  {
    id: 64,
    image: 'https://meninadeux.com/assets/img/cursos/twitter.webp',
    title: 'Twitter - Flight School',
    description: 'O Twitter Flight School tem tudo de que você precisa para ganhar mais do que apenas curtidas e retweets. Está tudo ao seu alcance: saiba como incentivar conversas, criar novas conexões, lançar uma campanha e muito mais!',
    link: 'https://www.twitterflightschool.com/student/catalog/list?category_ids=26635',
    category: ['todos'],
  },
  {
    id: 65,
    image: 'https://meninadeux.com/assets/img/cursos/udemy.webp',
    title: 'Udemy',
    description: 'Atualmente, na plataforma Udemy, você pode encontrar mais de 60 cursos gratuitos de UX/UI Design, sabia? Não sabia? Pois clica no link abaixo e veja você mesmo!',
    link: 'https://www.Udemy.com/pt/courses/design/user-experience/?price=price-free&sort=popularity&persist_locale=&locale=pt_BR',
    category: ['todos'],
  },
  {
    id: 66,
    image: 'https://meninadeux.com/assets/img/cursos/universidadesolides.webp',
    title: 'Universidade Sólides',
    description: 'A Sólides está oferecendo cursos focados em recursos humanos e gestão de pessoas. Atualmente, são 12 cursos gratuitos oferecidos, sendo eles: times de alto desempenho, soft skills e hard skills, cultura e comportamento, etc.',
    link: 'https://universidade.Solides.com.br',
    category: ['todos'],
  },
  {
    id: 67,
    image: 'https://meninadeux.com/assets/img/cursos/unova.webp',
    title: 'UNOVA',
    description: 'A UNOVA é uma plataforma de cursos gratuitos em várias áreas que fazem uso de recursos dinâmicos que trazem conteúdos educacionais que podem ser assistidos e consultados de forma online.',
    link: 'https://www.UNOVAcursos.com.br',
    category: ['todos'],
  },
  {
    id: 68,
    image: 'https://meninadeux.com/assets/img/cursos/usp.webp',
    title: 'USP gratuitos',
    description: 'Quer um certificado de uma das melhores faculdades do Brasil! A USP está oferecendo 19 cursos gratuitos a distância em diferentes áreas!',
    link: 'https://USPdigital.USP.br/apolo/apoListarCursoFormato?id_formato=dist',
    category: ['todos'],
  },
  {
    id: 69,
    image: 'https://meninadeux.com/assets/img/cursos/uxwritinghub.webp',
    title: 'UX Writing Hub (Inglês)',
    description: 'A UX Writing Hub oferece um curso de UX Writing gratuito onde você vai aprender sobre o básico de UX Writing e design de conteúdo, psicologia em UX, UX Writing Research e muito mais!',
    link: 'https://course. UXwritinghub.com/free_course',
    category: ['todos'],
  },
  {
    id: 70,
    image: 'https://meninadeux.com/assets/img/cursos/womakerscode.webp',
    title: 'Mais Mulheres em Tech',
    description: 'A Mais Mulheres em Tech é a 1ª plataforma brasileira criada por mulheres, com a missão para capacitar mulheres em tecnologia e inovação. São oferecidos vários cursos nas áreas de cloud e desenvolvimento! Aproveitem!',
    link: 'https://www.maismulheres.tech/collections',
    category: ['todos'],
  },
]

export const properties = {
  filtros,
  bootcampObjetc,
  cursoObjetc,
}
