// Components
import Head from 'next/head'

// Styles
import styled from '@/styles/Home.module.scss'
import SocialMedia from '@/components/sections/SocialMedia'
import News from '@/components/sections/News'

// Utilities
// Hooks
// Interfaces

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styled.containerHome}>
        <News />
        <SocialMedia />
      </main>
    </>
  )
}
