// Components
import Head from 'next/head'
import Title from '@/components/common/Title/Title'
import SubTitle from '@/components/common/Subtitle/SubTitle'

// Styles
import styled from '@/styles/Home.module.scss'
import styles from '@/styles/PropostaDeValor.module.scss'

// Utilities
// Hooks
// Interfaces

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styled.containerHome}>
        <section className={styles.proposta}>
          <div className={styles.propostaContainer}>
            <Title type="Default">Proposta de Valor</Title>
            <SubTitle type="Lg">
              O que é, como fazer e como ela pode mudar o seu negócio. Hoje, no
              Menina de UX repórter!
            </SubTitle>
          </div>
        </section>
      </main>
    </>
  )
}
